### ISSUE TITLE
[1.12.2] Disenchantment Texture is invisible?

### ISSUE THREAD

**Issue by D3nnis3n** [Impelon/Disenchanter#21] opened 2017-10-05 06:53 UTC
See the screenshot: 
https://ibb.co/jnZeQb

I do use optifine, but i have no choice, as playing on 4K Monitor does not work with my graphics Card for minecraft and i Need the rescaling.

**Comment by Impelon** [comment] 2017-10-05 09:11
Hm... wierd, I tested it with optifine as well and everything was fine. It was on the default settings tho...
What forge version are you using? 
How about if you disable the resourcepack you're using?

**Comment by D3nnis3n** [comment] 2017-10-05 09:43
I'm using 1503 Forge. I'm trying with my resource pack disabled this time. I already disabled the shaders, that didn't work.

**Comment by Impelon** [comment] 2017-10-05 10:13
Do you mean Forge 2503? That is the latest Forge version for 1.12.2 xD
It might have something to do with the forge version, so let me try out a few things.

**Comment by D3nnis3n** [comment] 2017-10-05 10:14
Yes, i meant that. I'm sorry.

**Comment by D3nnis3n** [comment] 2017-10-05 10:18
Bug is there without texture pack, too.

**Comment by Impelon** [comment] 2017-10-05 10:40
Hm... you might want to try to downgrade to the [recommended Forge version 2491](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html). 
But I do not think that will fix your problem, because I cannot reproduce the issue with any 1.12-forge version I tested (including 2503 and 2491). 
I would need you to post the startup-log so I can see, if I spot any issues there... 
I'd need ./logs/fml-client-latest.log

**Comment by D3nnis3n** [comment] 2017-10-05 10:43
I can not downgrade that far, i got mods that need Minimum 1501.
Here is my fml-client-latest.log

https://gist.github.com/D3nnis3n/bd3de03854ca19b4ed176c9e1911d036

**Comment by D3nnis3n** [comment] 2017-10-05 10:44
I also trief removing "FoamFix", as it deduplicates and works with textures - to no avail.

**Comment by Impelon** [comment] 2017-10-05 11:06
Maybe try [this](https://www.reddit.com/r/feedthebeast/comments/3dud3d/for_those_who_have_similar_issues_with_chisel_2/)?
The log is completely normal, no issues there. I suspect it is some kind of OptiFine setting...

**Comment by D3nnis3n** [comment] 2017-10-05 11:09
Did you try with Optifine C6 or C5?

I can't find that Option, tough. I got nothing like Chunk Loading = Smooth / Default in my Options.

I'm also wondering why yours is the only invisible block :( As you saw, i got somehwat 160 Mods installed, and mone got problems. Seems like i have to try around again with removing mods in bulk, urgh.

**Comment by Impelon** [comment] 2017-10-05 11:25
I'm using C6. You're right, the Chunk Loading option was for a past version (probably for 1.7.10) so never mind that...
Thing is I am not using OptiFine very often and I don't know about all the options and so on. You may wanna try a separate, clean installation with just OptiFine on default settings and Disenchanter to see if it works there. 

**_Caution: Rant_**
If not I'd guess it's some stupid graphics card problem... It's just wierd that this only happends to the Disenchantment Table. It uses the a copy of the model of the Enchantment Table. 
Granted the texture location is a bit unusual (see #12), but since the item loads no problem AND I do not see any texture loading issue in the log, I do not think that's the issue.

**Comment by Impelon** [comment] 2017-10-05 11:34
There is an _Lazy Chunk Loading_ option under _Performance_.

**Comment by D3nnis3n** [comment] 2017-10-05 11:47
Yeh, i found that, but i cannot Change this from Off to on - it just won't change.
I'm trying around with some mods :/

**Comment by Impelon** [comment] 2017-10-05 12:16
I've looked at some other things that came to mind, but with no results... 
I'm sorry I could not help you, but I honestly do not know what the issue is =I

**Comment by D3nnis3n** [comment] 2017-10-05 12:47
I'm at the Moment tracking it down to the mod that causes this behaviour and am hoping you can help when i managed that. I have nailedd it down to 5 mods. I'll tell you which one causes that when i'm done.

**Comment by D3nnis3n** [comment] 2017-10-05 12:52
It's fancy block particles. If removed, it works. I'll link my issue over there and back to here.

**Comment by D3nnis3n** [comment] 2017-10-05 12:52
https://github.com/TominoCZ/FancyBlockParticles/issues/15

**Comment by Impelon** [comment] 2017-10-05 13:41
I'll see what I can do =p
Atleast now I have a starting point xD

**Comment by Impelon** [comment] 2017-10-06 07:26
You might wanna try to disable the animation of the Disenchantment Table in FBP (maybe there is a config option? At least there is supposed to be an option...). 
Because maybe it might take some time until this will be fixed.

**Comment by Impelon** [comment] 2017-10-07 14:05
Well I'll close this for now I guess...

**Closed as completed by Impelon** 2017-10-07 14:05 UTC
Labels: incompatibility
